### PR TITLE
Upgrade to React 18.2.0

### PR DESCRIPTION
**Pull request by willopez**
Upgrade to React 18.2.0 and Fix some "Attempting to update an component the has been unmounted" errors.

### CODE REVIEW

**Comment by m-Ryan** [comment]
Thanks willopez. I pulled your PR to build, but got some errors. You can reproduce it with `yarn build`.
image

**Comment by willopez** [comment]
@m-Ryan Give it another go, I believe it should work correctly now.

**Review by m-Ryan — APPROVED** [review]

**Comment by m-Ryan** [comment]
Well done! @willopez 
I will merge it into the test environment first, and if there are no problems, it will be released this weekend.

**Comment by applibs** [comment]
I got this error:
`TS2694: Namespace 'React' has no exported member 'StatelessComponen`
at this line:
`const anotherComponentName = (AnotherComponent as React.StatelessComponent`
of file components.tsx

**Pull request merged**
