### PR TITLE
feat: moving mjml-browser out of easy-email-core

### PR DESCRIPTION
**Pull request by sambegin**
First of all, nice repo 👌  

I'd like to open the discussion and offer a potential solution to problems we've faced using this solution in a backend node environment. I've basically stumbled upon this same issue: https://github.com/zalify/easy-email/issues/122. 

Then I added the `import './windowMock';`.

We then encounter weird issues running node scripts and running our jest test suite. Both caused node script to not exit and hang infinitely as soon as we applied JSDOM window to nodeJS global.window object. Looking into it deeper, I did not understand why `mjml-browser` was actually imported in a backend environment. (The mjml-browser repository even states that this package should be used on the client-side)

Found out that the only reason this package was imported is because of the `MjmlToJson` function which in turn is only used for the `SourceCodePanel` in the `extensions` package. What I'm suggesting here:

- Make a major package update of this repository, removing the `mjml-browser` peer-dependencies of `easy-email-core`
- Move the `MjmlToJson` function in the `extensions` package
- Move tests and source files using this method into `extensions` package as well

Results: 
- Anyone who needs to use this package won't have to import a client-side dependency into node. 
- You **do not need the `windowMock` file** anymore to send email from a json generated by the editor

Let me know if that makes sense! Again, thanks for the effort put into this project!

### CODE REVIEW

**Review by sifrenette — APPROVED** [review]

**Review by wilau2 — APPROVED** [review]

**Comment by m-Ryan** [comment]
To handle mjml-browser, all you need to do is to create an alias like this: {"mjml-browser": "./node_modules/mjml"}.
 In fact, mjml-browser doesn't require a browser enviroment, but it's used by parseXMLtoBlock, which converts a part of mjml into its corresponding json format.

image

**Comment by sambegin** [comment]
Hey!

I still it would be worth reducing the dependencies from easy-email-core. Doing this change, we do not need to add `jsdom`,  `mjml-browser` + the windowMock hack in a node environment. What do you think ?

**Comment by m-Ryan** [comment]
You are right, I have checked MjmlToJson and it doesn't need to be included in the core package. Please update the documentation as well: https://github.com/zalify/easy-email/blob/master/packages/easy-email-core/readme.md
Thanks. @sambegin

**Comment by sambegin** [comment]
I'll have a look into it! 

I'll also see why the CI doesn't pass (everything was working locally but I didn't have the CI view in github until now)

**Comment by m-Ryan** [comment]
> I'll have a look into it!
> 
> I'll also see why the CI doesn't pass (everything was working locally but I didn't have the CI view in github until now)

image
@sambegin

**Comment by sambegin** [comment]
Yep, I see it now. Looking into it

**Comment by sambegin** [comment]
@m-Ryan  It seems I have a github action cache issue. Tried multiple things to make it work but one thing I cannot try is to flush the cache in the actions page (I do not have access to this) : 

Do you think you would be able to clear the cache and see how it goes? 

Screenshot 2023-03-08 at 9 04 33 AM

**Comment by wilau2** [comment]
We are still investigating why the build is failing, trying to fix this up

**Comment by sambegin** [comment]
@m-Ryan  I think we're good to go. 

I've:
- updated core + extensions readme to reflect the MjmlToJson move 
- updated github actions to run both test suites in each package 
- Fixed a small typo in the core readme
- Removed comments in jest.config files (it just felt easier to read and review and anyway we can always go back to the link that redirect to jest documentation for that)

Let me know if you see something missing 👌

**Comment by m-Ryan** [comment]
Great job.  
image

@sambegin @wilau2  Please check

**Comment by sambegin** [comment]
@m-Ryan , since the `MjmlToJson` function has moved from `core` to `extensions` package, I think we should have made a **major**  version update.

**Pull request merged**
